imagenet_templates_game = [
    'a rendering of a {}.',
    'a rendering of the {}.',
    'a rendition of a {}.',
    'a rendition of the {}.',
    'a pixelated photo of a {}.',
    'a pixelated photo of the {}.',
    'graffiti of a {}.',
    'graffiti of the {}.',
    'a tattoo of a {}.',
    'a tattoo of the {}.',
    'the embroidered {}.',
    'a drawing of a {}.',
    'a drawing of the {}.',
    'a painting of a {}.',
    'a painting of the {}.',
    'a doodle of a {}.',
    'a doodle of the {}.',
    'a origami {}.',
    'the origami {}.',
    'the toy {}.',
    'a toy {}.',   
    'the toy {}.',
    'art of a {}.',
    'art of the {}.',
    'a cartoon of {}.',
    'the cartoon of {}.',
    'a sketch of a {}.',
    'a sketch of the {}.',
    'a character of a {} in a cartooon.',
    'a character of the {} in a cartoon.',
    'a {} in a video game.',
    'a {} in a video game.',
    'a character of a {} in a video game.',
    'a character of the {} in a video game.',   
    'a character of a {} in a game.',
    'a character of the {} in a game.',
    'a 3D {} designed for a game.',
    'the 3D {} designed for a game.',
    'a fantasy-style {} in a game.',
    'the fantasy-style {} in a game.',
    'a stylized {} in a vibrant game world.',
    'the stylized {} in a vibrant game world.',
    'a colorful {} in a game environment.',
    'the colorful {} in a game environment.',
    'a {} in a sci-fi game.',
    'the {} in a sci-fi game.',
    'a hand-drawn {} in a game.',
    'the hand-drawn {} in a game.',
    'a cartoonish {} in a whimsical game.',
    'the cartoonish {} in a whimsical game.',
    'a realistic {} in a game.',
    'the realistic {} in a game.',
    'a glowing {} in a magical game.',
    'the glowing {} in a magical game.',
    'a dynamic {} in an action game.',
    'the dynamic {} in an action game.',
    'a detailed {} in a fantasy RPG.',
    'the detailed {} in a fantasy RPG.',
    'a mystical {} in a magical forest game.',
    'the mystical {} in a magical forest game.',
    'an enchanted {} in a magical realm.',
    'the enchanted {} in a magical realm.',
    'a cyberpunk-style {} in a futuristic game.',
    'the cyberpunk-style {} in a futuristic game.',
    'a retro-style {} in a pixel art game.',
    'the retro-style {} in a pixel art game.',
    'an abstract {} in an indie game.',
    'the abstract {} in an indie game.',
    'a unique {} designed for a puzzle game.',
    'the unique {} designed for a puzzle game.',
]


imagenet_templates = [
    'a bad photo of a {}.',
    'a sculpture of a {}.',
    'a photo of the hard to see {}.',
    'a low resolution photo of the {}.',
    'a rendering of a {}.',
    'graffiti of a {}.',
    'a bad photo of the {}.',
    'a cropped photo of the {}.',
    'a tattoo of a {}.',
    'the embroidered {}.',
    'a photo of a hard to see {}.',
    'a bright photo of a {}.',
    'a photo of a clean {}.',
    'a photo of a dirty {}.',
    'a dark photo of the {}.',
    'a drawing of a {}.',
    'a photo of my {}.',
    'the plastic {}.',
    'a photo of the cool {}.',
    'a close-up photo of a {}.',
    'a black and white photo of the {}.',
    'a painting of the {}.',
    'a painting of a {}.',
    'a pixelated photo of the {}.',
    'a sculpture of the {}.',
    'a bright photo of the {}.',
    'a cropped photo of a {}.',
    'a plastic {}.',
    'a photo of the dirty {}.',
    'a jpeg corrupted photo of a {}.',
    'a blurry photo of the {}.',
    'a photo of the {}.',
    'a good photo of the {}.',
    'a rendering of the {}.',
    'a {} in a video game.',
    'a photo of one {}.',
    'a doodle of a {}.',
    'a close-up photo of the {}.',
    'a photo of a {}.',
    'the origami {}.',
    'the {} in a video game.',
    'a sketch of a {}.',
    'a doodle of the {}.',
    'a origami {}.',
    'a low resolution photo of a {}.',
    'the toy {}.',
    'a rendition of the {}.',
    'a photo of the clean {}.',
    'a photo of a large {}.',
    'a rendition of a {}.',
    'a photo of a nice {}.',
    'a photo of a weird {}.',
    'a blurry photo of a {}.',
    'a cartoon {}.',
    'art of a {}.',
    'a sketch of the {}.',
    'a embroidered {}.',
    'a pixelated photo of a {}.',
    'itap of the {}.',
    'a jpeg corrupted photo of the {}.',
    'a good photo of a {}.',
    'a plushie {}.',
    'a photo of the nice {}.',
    'a photo of the small {}.',
    'a photo of the weird {}.',
    'the cartoon {}.',
    'art of the {}.',
    'a drawing of the {}.',
    'a photo of the large {}.',
    'a black and white photo of a {}.',
    'the plushie {}.',
    'a dark photo of a {}.',
    'itap of a {}.',
    'graffiti of the {}.',
    'a toy {}.',
    'itap of my {}.',
    'a photo of a cool {}.',
    'a photo of a small {}.',
    'a tattoo of the {}.',
]


imagenet_templates_game_l = [    
    'a low-poly {} in a video game.',
    'a cartoonish {} in a whimsical game.',
    'a pixelated photo of a {} in a game.',
    'a toy {} in a video game.',
    'a stylized {} in a vibrant game world.',
    'a 3D {} designed for a game.',
    'a simple polygonal {} in a game.',
    'a choppy {} with minimal details in a game.',
    'a retro-style {} in a pixel art game.',
    'a blocky {} in a video game.',
    'a cartoon of {} in a video game.',
    'a doodle of a {} in a game.',
    'a Minecraft-like {} in a video game.',
    'a colorful {} in a game environment.',
    'a toy-like {} with blocky features in a game.',
    'a low-resolution {} in a game.',
    'a blocky {} with flat colors in a game.',
    'a simple {} in a video game.',
    'a stylized {} in a casual game.',
    'a cartoon character of a {} in a game.',
]

imagenet_templates_game_m = [
    'a stylized {} in a vibrant game world.',
    'a medium-resolution {} designed for a game.',
    'a semi-detailed {} in a fantasy game.',
    'a cartoonish {} with refined details in a game.',
    'a semi-realistic {} in a video game.',
    'a colorful {} in a game scene.',
    'a balanced-detail {} in a casual game.',
    'a detailed {} in a fantasy RPG.',
    'a mid-poly {} with detailed patterns in a game.',
    'a dynamic {} in an action game.',
    'a hand-drawn {} in a game.',
    'a stylized {} with moderate detail in a game.',
    'a slightly stylized {} for a video game.',
    'a vibrant {} rendered for a game.',
    'a realistic {} in a game.',
    'a smooth-textured {} with moderate quality in a game.',
    'a semi-detailed {} in a fantasy RPG.',
    'a colorful {} in a game environment.',
    'a cartoonish {} in a whimsical game.',
    'a mid-quality {} with handcrafted textures.',
]

imagenet_templates_game_h = [
    'a photorealistic {} with intricate textures in a game.',
    'a cinematic {} rendered with ultra detail in a game.',
    'a AAA-quality {} for a next-gen game.',
    'an ultra-high-resolution {} in 4K in a game.',
    'a highly-detailed {} with realistic lighting in a game.',
    'a cutting-edge {} with PBR textures in a game.',
    'a hyper-realistic {} with advanced shaders in a game.',
    'a premium-quality {} for a blockbuster game.',
    'an immersive {} with complex details in a game.',
    'a true-to-life {} for a simulation game.',
    'a realistic 3D {} with lifelike features in a game.',
    'a visually stunning {} with HDR effects in a game.',
    'an ultra-realistic {} in a sci-fi game.',
    'a photorealistic {} in a video game.',
    'a meticulously-detailed {} in a high-end game.',
    'a cinematic {} rendered for a realistic experience in a game.',
    'an ultra-realistic {} in a futuristic game.',
    'a premium-quality {} in a cutting-edge VR game.',
    'a next-gen {} designed for VR gaming.',
    'a hyper-realistic {} in a futuristic game.',
]

template_game_mapping = {
    "low": imagenet_templates_game_l,
    "mid": imagenet_templates_game_m,
    "high": imagenet_templates_game_h,
}